### ISSUE TITLE
Switch taxonomy to WoRMS

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#454]
The taxonomy should be using WoRMS

Steps:

- [x] export a list of taxa used (i.e. that are used in `obj_head` and `objectsclassifhisto`), together with their lineage (all parents until the root)
- [x] make a dump from WoRMS (through their API? ask them for a dump?)
- [x] match each taxon to WoRMS
- [ ] for taxa that do not match, try to match the parent, the grand parent etc. until a match is found

- [ ] erase the current taxonomy and replace it by a dump from WoRMS
- [ ] add the missing branches = all taxa between an existing taxon in WoRMS and the taxon used in EcoTaxa. For example, for `Living > Eukaryota > Crustacea > Copepoda > Copepodites > Stage 5`, `Copepoda` is in WoRMS, `Stage 5` and `Copepodites` are not and should be added, we don't care about `Crustacea` and above because `Copepoda` is in WoRMS and WoRMS will provide the lineage above it.

- [ ] from the correspondance between current taxa and taxa in the new "WoRMS+missing ones" taxonomy, derive a correspondance between the old and new `taxo_ids` in EcoTaxa.
- [ ] check that all ids used have a match
- [ ] change all taxo ids in `obj_head` and `objectsclassifhisto`

**Comment by grololo06** [comment]
Our taxonomy table is not only filled with taxonomy entries, e.g. the famous "temp001" and other classification goodies. That's why they are named "categories" in various places, which is good IMHO. So instead of replacing the taxo ids in DB, I think we're going to simply keep somehow the association (our_id, aphiaId).
BTW, WoRMS lookup returns sometimes multiple "possible" aphiaIDs for a given name, with a field to indicate the "quality" of the match. So it's a(nother) tricky case to manage.
E.g. http://www.marinespecies.org/rest/AphiaRecordsByName/annelida?marine_only=true
Anyway, experimenting will be needed before deciding on the "final" form of this transformation.

**Comment by jiho** [comment]
The morpho taxa (everything under not-living and the `larvae`, `part`, etc.) will be resolved by the process above (look for a WorMS match in the ancestors; it is just that, for the non-living stuff, no match will be found and the parent is therefore the root).

We don't just need a correspondence for each taxon, because the structure of the hierarchy is different in WoRMS and us, and we want to get rid of our structure and use the one from WoRMS.

**Comment by grololo06** [comment]
Linked with #456, I guess people will be quite unhappy once we apply the algorithm described above and all their careful "with eggs" category is merged with base animal species. So we need to keep current IDs at least during the experiment/clean-up/clear-up phase.

**Comment by grololo06** [comment]
First round of exploration (simple match by name with WoRMS) outcome is visible at https://ecotaxa.obs-vlfr.fr/api/taxa/matches2
After discussion, it looks like we have to transition progressively to WoRMS, e.g. by adding a tool to expose/validate the changes impacting the users.
E.g. rename of Poecilostomatoida (not accepted) to Ergasilida
During the transition, it should be encouraged to add accepted taxa from WoRMS.

**Comment by grololo06** [comment]
Comes to me: Quoting 'we don't care about Crustacea and above because Copepoda is in WoRMS and WoRMS will provide the lineage above it.' -> We should care if some identified objects are in the path.
e.g. us: A (0) > B (0) > C (30) > D (400) > E (5) > F (7)
E and F are morpho -> don't match
A, B and D are 'accepted' i.e. Aw == A, Bw == B, Dw == D
Dw lineage is Aw > Bw > Dw

**Comment by jiho** [comment]
Add one check: for taxa that have an exact match in WoRMS check that it is a 1:1 match (one taxon in worms matches one and only one taxon in EcoTaxa and conversely)

Example of problematic cases:
Bilvavia : 2 in EcoTaxa that match the same in WoRMS.
Ctenophora: many in EcoTaxa and in WoRMS.

**Comment by jiho** [comment]
Unaccepted taxa in WoRMS need to be kept in the EcoTaxa database. This would allow to avoid recreating taxa in EcoTaxa that were deprecated (ex: Neoceratium -> Tripos).

**Comment by jiho** [comment]
Deal with the case of two ecotaxa ids that should be merged in the same worms id. Review all the table to change the ids?

**Comment by jiho** [comment]
Do we keep `alternate representation`? Check with EurOBIS/EmodnetBiol

**Comment by grololo06** [comment]
Superseded by #709
