### ISSUE TITLE
Collections - deal with temporary classes

### ISSUE THREAD

**Issue by rkiko** [ecotaxa/ecotaxa_dev#623]
Temporary classes between projects are not homogeneous, if projects are merged to collections, this needs to be dealt with.

**Comment by grololo06** [comment]
Projects are not merged to collections, as of today collections are "just" a set of homogeneous projects. So far the categories which cannot be mapped in WoRMS are simply ignored, so the temp ones should not be an issue. Still I assign @jiho in case it rings a bell to him.

**Comment by grololo06** [comment]
Present issue was not linked to #519 so now it is :)

**Comment by jiho** [comment]
Collections are for export but also would allow to browse the images. In that sense, if `t001` in proj A is a square `t001` in proj B is a circle and proj A and B are made into a collection, the `t001` category of the collection will have squares and circles.

This is fine by me and will entice people to (i) empty t00* categories, (ii) create categories with descriptive names for those that they really cannot name (e.g. `dark blob with halo`).

**Comment by jiho** [comment]
Of course if a t00* category that is heterogeneous is exported, it will be a mess. But t00* categories will likely be remapped   before export (see #599)

**Comment by rkiko** [comment]
Not sure what good collections are for, if one can not sort in them ... I +- never just browse through a project ... And the data can be merged after the export. So, building collections without the long-term goal to enable sorting is in my view a waste of time.

I think one could do temporary classes per project in the collection; so t001.m106, t001.m105, ... and somehow enable merging if it was homogenized. Or enable sorting by cruise, so that one can tease merged ones apart easily. That is possible anyhow, I think.

**Comment by rkiko** [comment]
Hi,
sorry, could not react as fast as this was closed. I added a comment along the lines that collections in the long-run need to enable sorting…

Otherwise, this work is in my view a cul de sac.

Cheers,
Rainer.

**Comment by jiho** [comment]
Yes, collections will allow sorting (if permissions on all underlying projects allow it).

What I am saying here is that `t00*` are stop gap solutions to put stuff that you don't know where to put. I don't what to encourage people to consider their project to be "sorted" if 10% of the stuff lives in the temp classes. What should be done is try to name them taxonomically and, if that this not possible, name them morphologically and branch them somewhere relevant in the tree (even if it can only be under living, it is better than under temporary).

Making a function to disambiguate the temp from various projects will encourage people to just leave them there (and they'll remember that `t001.m106` is round transparent stuff and `t001.m105` is long dark stuff (just like they remember now that `t001` in project `m106` is round transparent stuff etc.). This is bad because only the people who sorted know this. It would be much better to actually create a category `round-transparent` branched under `living` and use this across projects. And, if that is done, they it will be OK within a collection.

**Comment by picheral** [comment]
I do agree with : "Collections are for export but also would allow to browse the images. In that sense, if t001 in proj A is a square t001 in proj B is a circle and proj A and B are made into a collection, the t001 category of the collection will have squares and circles.

This is fine by me and will entice people to (i) empty t00* categories, (ii) create categories with descriptive names for those that they really cannot name (e.g. dark blob with halo)."

**Comment by jiho** [comment]
The temp classes are not ignored but just treated like other classes, e.g. if you create a collection from a project in which Copepoda is a mix of all Copepods and another where Copepoda is only the copepods that cannot be sorted in further classes, the Copepoda class in the collection will be a mix of different things.

That said, I like the idea of "enforcing" the emptying of temporary classes so https://github.com/ecotaxa/ecotaxa_dev/issues/662

**Comment by rkiko** [comment]
Are you saying that if one project only has copepoda and the other has also different calanoid families, then these get bunched together under copepoda? For me, that would be bad. Why would you bunch up the families? 

I would actually like to have a choice if I want to aggregate to a certain level or have everything as fine as possible. Maybe, I would like to get everything sorted into families, then I would need to redo the sorting of stuff already at family level, because in one project it is not at family level? So, I think another task/tool needs to be generated that allows for the definition of the aggregation level of the collection.

Hmm, further thinking: how do you propagate this back to original projects? If you aggregate at coarser level than the original projects and sort in them and then propagate back, you actually screw up the original sorting. I think we always want to sort to finer levels, not to coarser levels. Viewing is OK at aggregated levels, but not sorting... So, if a collection should be used for sorting, it should have all the details ...

**Comment by jiho** [comment]
I think we need a live discussion 😉

In a few words:
- collections just "view" the underlying data from projects; no aggregation or renaming
- when one can sort in a collection (because that person has the permission to sort on the underlying projects), the sorting is reflected in the projects (because these are the same objects)
- aggregation/renaming will be possible at _export_, in projects and in collections

**Comment by rkiko** [comment]
Then I just misunderstood you ;)
