### ISSUE TITLE
Problems with EMODnet defined collections

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_dev#634]
DYFAMED
https://www.emodnet-biology.eu/data-catalog?module=dataset&dasid=6508

290
291
296
2975 **<---- Does not exist**
298
299
333
334
871

Régent
https://www.emodnet-biology.eu/data-catalog?module=dataset&dasid=6506

15
130
2836 **<-- Contains samples referenced elsewhere**
745
773
336
672
754
769
771
772
776
777
895
898
2810  **<-- Contains samples referenced elsewhere**
2814  **<-- Contains samples referenced elsewhere**
2815  **<-- Contains samples referenced elsewhere**
2823  **<-- Contains samples referenced elsewhere**
2824  **<-- Contains samples referenced elsewhere**
2825  **<-- Contains samples referenced elsewhere**
2826  **<-- Contains samples referenced elsewhere**
2827  **<-- Contains samples referenced elsewhere**
2828  **<-- Contains samples referenced elsewhere**
2829  **<-- Contains samples referenced elsewhere**
2830  **<-- Contains samples referenced elsewhere**
2831  **<-- Contains samples referenced elsewhere**
2833  **<-- Contains samples referenced elsewhere**
2834  **<-- Contains samples referenced elsewhere**
2835  **<-- Contains samples referenced elsewhere**
2715  **<-- Contains samples referenced elsewhere**
768

PNMIR Cruises
https://www.emodnet-biology.eu/data-catalog?module=dataset&dasid=6511

To export as occurence only (the concentrations cannot be trusted).

434 **<-- Contains not-validated objects**
435
436
443
468 **<-- Contains not-validated objects**
826
1244
442

**Comment by grololo06** [comment]
Flowcam
https://www.emodnet-biology.eu/data-catalog?module=dataset&dasid=6517

326
327
328
329
330
331
332

decimalLatitude: 47.395433
decimalLongitude: 46.88925
eventID: 20131127_1549_udw_a_2 (project 332)
issue: Marine Taxa on Land

**Comment by jiho** [comment]
Let's solve them 1 by 1.

- 2975 : seems to have been a typo or a temporary one. The list is OK without it
- Flowcam = Roscoff = we don't (immediately) care 😉; the data is 10% sorted anyway so metadata is the least of the problems
- Regent, projects in with ids in 2*** = mistake on my part. Those are subsets
- PNMIR: only validated objects are taken into account. The unvalidated ones correspond to full samples which are not validated. Possible?

Overall, this led me to review the list and correct some mistakes/changes since I first generated it. The one in #426 is the one on which the metadata and taxo QC has been done. Sorry...

**Comment by grololo06** [comment]
OK, cleared-up in #426
