### ISSUE TITLE
Sorting by "Category Name" is very slow : Postgresql 13 query performance regression

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_dev#650]
Since a few weeks, a PG 13 DB is used for querying from some parts of EcoTaxa, while the 'old' PG 11 is used for writing and reading in other parts. The PG 13 is on SSDs while the PG 11 is on HDD. The PG 13 is a replica of the PG 11.
I noticed that querying using "Category Name" as sort takes ages.
The generated query is:
```
SELECT obh.objid, acq.acquisid, sam.sampleid , 0 AS total
      FROM obj_head obh
  JOIN samples sam ON sam.projid = 3365
  JOIN acquisitions acq ON acq.acq_sample_id = sam.sampleid
JOIN taxonomy txo ON txo.id = obh.classif_id 
WHERE obh.acquisid = acq.acquisid
ORDER BY name asc, obh.objid ASC OFFSET 0 LIMIT 100;
```
On the theoretically slowest hardware:
```
psql (13.2 (Ubuntu 13.2-1.pgdg18.04+1), serveur 11.11 (Ubuntu 11.11-1.pgdg18.04+1))
Connexion SSL (protocole : TLSv1.3, chiffrement : TLS_AES_256_GCM_SHA384, bits : 256, compression : désactivé)
Saisissez « help » pour l'aide.

ecotaxa=# SELECT obh.objid, acq.acquisid, sam.sampleid , 0 AS total
ecotaxa-#       FROM obj_head obh
ecotaxa-#   JOIN samples sam ON sam.projid = 3365
ecotaxa-#   JOIN acquisitions acq ON acq.acq_sample_id = sam.sampleid
ecotaxa-# JOIN taxonomy txo ON txo.id = obh.classif_id 
ecotaxa-# WHERE obh.acquisid = acq.acquisid
ecotaxa-# ORDER BY name asc, obh.objid ASC OFFSET 0 LIMIT 100;
...
 179964271 |   129575 |   155121 |     0
 179964673 |   129576 |   155124 |     0
(100 lignes)

Temps : 248,921 ms
ecotaxa=# 
```

On the fastest one and latest PG version:

```
psql (13.2 (Ubuntu 13.2-1.pgdg18.04+1))
Connexion SSL (protocole : TLSv1.3, chiffrement : TLS_AES_256_GCM_SHA384, bits : 256, compression : désactivé)
Saisissez « help » pour l'aide.

ecotaxa=# SELECT obh.objid, acq.acquisid, sam.sampleid , 0 AS total
ecotaxa-#       FROM obj_head obh
ecotaxa-#   JOIN samples sam ON sam.projid = 3365
ecotaxa-#   JOIN acquisitions acq ON acq.acq_sample_id = sam.sampleid
ecotaxa-# JOIN taxonomy txo ON txo.id = obh.classif_id 
ecotaxa-# WHERE obh.acquisid = acq.acquisid
ecotaxa-# ORDER BY name asc, obh.objid ASC OFFSET 0 LIMIT 100;
 179964050 |   129575 |   155121 |     0
 179964271 |   129575 |   155121 |     0
 179964673 |   129576 |   155124 |     0
(100 lignes)

Durée : 244948,283 ms (04:04,948)
```

Which is nearly 1000 times more :(
The culprit here is the use from the optimizer of https://www.postgresql.org/docs/13/runtime-config-query.html#GUC-ENABLE-INCREMENTAL-SORT
Disabling the feature in PG13 gives:
```

SET LOCAL enable_incremental_sort=FALSE;
...
 179964050 |   129575 |   155121 |     0
 179964271 |   129575 |   155121 |     0
 179964673 |   129576 |   155124 |     0
(100 lignes)

Temps : 241,648 ms
ecotaxa=*#  
```

**Comment by grololo06** [comment]
Fixed globally (for now) in `"/etc/postgresql/13/main/postgresql.conf"` and config reloaded.

**Comment by grololo06** [comment]
Still true with current version:
serveur 13.5 (Ubuntu 13.5-1.pgdg18.04+1))
```
ecotaxa=# begin;                                 
SET LOCAL enable_incremental_sort=TRUE;
BEGIN
Temps : 0,513 ms
SET
Temps : 0,183 ms
ecotaxa=*# SELECT obh.objid, acq.acquisid, sam.sampleid , 0 AS total
      FROM obj_head obh
  JOIN samples sam ON sam.projid = 3365
  JOIN acquisitions acq ON acq.acq_sample_id = sam.sampleid
 JOIN taxonomy txo ON txo.id = obh.classif_id 
WHERE obh.acquisid = acq.acquisid
 ORDER BY name asc, obh.objid ASC OFFSET 0 LIMIT 100;
...
Durée : 123490,086 ms (02:03,490)
```

**Comment by grololo06** [comment]
Still true with 13.6

`Durée : 121583,692 ms (02:01,584)
`

**Comment by grololo06** [comment]
Still true with 13.9: serveur 13.9 (Ubuntu 13.9-1.pgdg18.04+1))
```
ecotaxa=# begin;                                                   
BEGIN
Temps : 0,300 ms
ecotaxa=*# SET LOCAL enable_incremental_sort=TRUE;                  
SET
Temps : 0,263 ms
ecotaxa=*# SELECT obh.objid, acq.acquisid, sam.sampleid , 0 AS total
      FROM obj_head obh
  JOIN samples sam ON sam.projid = 3365
  JOIN acquisitions acq ON acq.acq_sample_id = sam.sampleid
JOIN taxonomy txo ON txo.id = obh.classif_id 
WHERE obh.acquisid = acq.acquisid
ORDER BY name asc, obh.objid ASC OFFSET 0 LIMIT 100;
...
 180038004 |   129650 |   155066 |     0
(100 lignes)

Durée : 123777,868 ms (02:03,778)

```

**Comment by grololo06** [comment]
Utterly strange, when asking for more rows it's faster:
```
ecotaxa=# begin; SET LOCAL enable_incremental_sort=TRUE;      
BEGIN
Temps : 0,303 ms
SET
Temps : 0,176 ms
ecotaxa=*# SELECT obh.objid, acq.acquisid, sam.sampleid , 0 AS total
      FROM obj_head obh
  JOIN samples sam ON sam.projid = 3365
  JOIN acquisitions acq ON acq.acq_sample_id = sam.sampleid
JOIN taxonomy txo ON txo.id = obh.classif_id 
WHERE obh.acquisid = acq.acquisid
ORDER BY name asc, obh.objid ASC OFFSET 0 LIMIT 350; end;
...
 179935858 |   129589 |   155120 |     0
 179935859 |   129589 |   155120 |     0
(350 lignes)

Temps : 310,333 ms
COMMIT
Temps : 0,275 ms
ecotaxa=# 
```
It seems that the optimizer has a special mode for the _n_ first rows which is buggy.

**Comment by fchahun** [comment]
No, this is not a bug.  This is due to the query semantics: a LIMIT clause brings a significant reduction of server processing time **only** if it is not associated with an ORDER BY clause that implies a global sort on the **whole** table. 
In a query with a global ORDER BY clause,  all the elementary operation nodes of the query plan up to the "sort" node necessarily ignore the LIMIT clause (see EXPLAIN). Then the last node of the plan implements the LIMIT by returning only the N firts rows after sorting, and this has a negligible cost on the server side  (of course, LIMIT has major influence on  server => client transmission overhead)
If the ORDER BY clause is suppressed, the query plan changes drastically and the LIMIT implications are accounted for in cost estimations for all nodes of the plan.

**Comment by grololo06** [comment]
> No, this is not a bug. This is due to the query semantics: a LIMIT clause brings a significant reduction of server processing time **only** if it is not associated with an ORDER BY clause that implies a global sort on the **whole** table. In a query with a global ORDER BY clause, all the elementary operation nodes of the query plan up to the "sort" node necessarily ignore the LIMIT clause (see EXPLAIN). Then the last node of the plan implements the LIMIT by returning only the N firts rows after sorting, and this has a negligible cost on the server side (of course, LIMIT has major influence on server => client transmission overhead) If the ORDER BY clause is suppressed, the query plan changes drastically and the LIMIT implications are accounted for in cost estimations for all nodes of the plan.

There is order by and limit in both cases, just the _value_ (100 vs 350) changes.

**Comment by fchahun** [comment]
In my copy of the DB on PG 15 (with bivariate correlation statistics creted), I cannot observe any change in query plan nor any significant difference in execution time between these two cases (100 vs 350). See attachments obtained by EXPLAIN(BUFFERS, ANALYZE, VERBOSE).
Is there any change between the two plans (and buffer access patterns) on PG 13?

[plan_350.txt](https://github.com/ecotaxa/ecotaxa_front/files/10977091/plan_350.txt)
[plan_100.txt](https://github.com/ecotaxa/ecotaxa_front/files/10977093/plan_100.txt)

**Comment by grololo06** [comment]
Production DB:
[plan350.txt](https://github.com/ecotaxa/ecotaxa_front/files/10977152/plan350.txt)
[plan100.txt](https://github.com/ecotaxa/ecotaxa_front/files/10977204/plan100.txt)
Obviously the conditions are different on your local DB.

**Comment by fchahun** [comment]
In your case, the "Incremental sort" pattern appears in the "plan_100" and not in the "plan_350". I thought it was disabled at the global config level?

You should add BUFFERS to the EXPLAIN statement [=> explain(analyze, buffers, verbose) ] so that we get a full picture of the difference between plans.

In any case, EXPLAIN ANALYZE reveals major estimation errors between **predicted** and **observed** row counts in both plans (with predicted >> observed) . This indicates that the query planner works in bad conditions where available statistics are either obsolete or unsufficient.  The query plan is therfore very unstable and subject to change depending on unpredictable thresholds. 

Things should come back to normal if you declare the 3 bivariate statistics  (with adequate sampling thresholds) as I suggested in a recent mail, and run ANALYZE  on concerned tables.

**Comment by grololo06** [comment]
> In your case, the "Incremental sort" pattern appears in the "plan_100" and not in the "plan_350". I thought it was disabled at the global config level?

It's a set local, pls re-read the .txt first lines.

> 
> You should add BUFFERS to the EXPLAIN statement [=> explain(analyze, buffers, verbose) ] so that we get a full picture of the difference between plans.
> 
> In any case, EXPLAIN ANALYZE reveals major estimation errors between **predicted** and **observed** row counts in both plans (with predicted >> observed) . This indicates that the query planner works in bad conditions where available statistics are either obsolete or unsufficient. The query plan is therfore very unstable and subject to change depending on unpredictable thresholds.
> 
> Things should come back to normal if you declare the 3 bivariate statistics (with adequate sampling thresholds) as I suggested in a recent mail, and run ANALYZE on concerned tables.

**Comment by fchahun** [comment]
_> It's a set local, pls re-read the .txt first lines._

OK, then "incremental sort" is locally allowed in both queries. 

But this does not change the analysis: plan instability based on unpredictable thresholds due to inaccurate selectivity estimates (based on statistics).  
I checked all PG release notes since 13.0 and there was no code change  in the "incremental sort" feature after 13.2
However, I might have to recreate a V13 version on the DB to be able to be get meaningful comparisons, since at least the Btree index sizes are different.

**Comment by grololo06** [comment]
Hello, I think that if you _remove_ somehow the statistics, the bug could show as well in PG15, but it's just a guess.

**Comment by fchahun** [comment]
Hello,
Yes, indeed, I can reproduce the problem on PG 15 by suppressing the bivariate (correlation) statistics previously created (in the same way as yous should see it it disappear if you create those statistics on your PG 13):

```
DROP statistics "sampleid_projid_xstats";
DROP statistics "acquisid_acq_sample_id_xstats";
DROP statistics "acquisid_classif_id_xstats";
```

Then I get the same big discrepancy that you observe between the two plans (see attached files):

- LIMIT = 100 => query evaluation time 1177 secs with incremental sort & very inefficient plan involving huge estimation errors  in row numbers on at least 2 nodes (x142 & x417) , check on https://explain.depesz.com)
- LIMIT = 350 => query evaluation time 1,2 secs without incremental & somewhat better plan, but still with significant estimation errors  in row numbers on 2 nodes (x99  & x74)

This observation is consistent with the fact that there was no change in the "incremental sort" code between PG 13.2. and PG 15.2.

However, you should not see this behavior as a **bug**, is the sense of something you could realistically expect to see corrected in a future version of PG by a fix in the planner code.  From the PG designers point of view, this is rather a **feature**  (the way PG planner works) ... which has unfortunate side-effects when statistical information on distribution/correlation of criteria used in the query is unavailable or inexact.

When the incremental sort feature was introduced in PG 13, this just opened a new path in the graph of all possible execution paths for the query. The fact that the planners takes a **wrong** path is, as always, caused by flawed cost estimates, the root cause being that the distribution statistics (on which cost estimations are based) are themselves flawed of unsufficient.

For pedagogical purposes, I implemented the cost estimation logic of the PG planner on an Excel spreadsheet (for simple query cases) based on analysis of its source code. This tool demonstrates very well how a single unit change on a row count can trigger a brutal shift from plan A to plan B. It also illustrates the amount of cost misestimation when non-independant criteria are in involved in the query and no bivariate correlation ("extended") statistics are available.

Of course, such estimation errors only have visible effects on **large** tables... but unfortunately the EcoTaxa tables **do fall** into this category.

[plan_100_PG15_without_stats.txt](https://github.com/ecotaxa/ecotaxa_front/files/10985269/plan_100_PG15_without_stats.txt)
[plan_350_PG15_without_stats.txt](https://github.com/ecotaxa/ecotaxa_front/files/10985270/plan_350_PG15_without_stats.txt)

**Comment by fchahun** [comment]
On this topic and the frustration it usually generates, read: https://news.ycombinator.com/item?id=28489340

As a possible solution,  see https://github.com/postgrespro/sr_plan for an open source extension allowing to lock PG query plans.

**Comment by fchahun** [comment]
A question I did not ask: what is the status of ANALYZE history (and hence basic statistics) on the production base?  You can see this in:

```
SELECT schemaname, relname, last_vacuum, last_autovacuum, last_analyze, last_autoanalyze, n_dead_tup, n_live_tup,
round(100*n_dead_tup::numeric/greatest(1, n_live_tup + n_dead_tup), 1) AS dead_tuple_ratio, n_mod_since_analyze
FROM pg_stat_user_tables
WHERE schemaname IN ('public')
ORDER BY schemaname DESC, relname ASC
```
